<?php

namespace AppBundle\Repository;

/**
 * InventorySlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventorySlotRepository extends \Doctrine\ORM\EntityRepository
{
}
